# Generated by Django 3.1.1 on 2020-09-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioHome', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
